s1=set([1,2,3,4,5,6])
s2=set([4,5,6,7,8,9])
ans=s1.union(s2)
ans1=s1.intersection(s2)
ans3=s1.difference(s2)
print(ans)
print(ans1)
print(ans3)

s=set(input())
alpha=set("abcdefghijklmnopqrstuvwxyz")
diff=sorted(alpha.difference(s))
print(''.join(diff))
